# Generated by Django 3.2 on 2023-07-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField(verbose_name='Сокращаемая ссылка')),
                ('short_url', models.SlugField(unique=True, verbose_name='Короткая ссылка')),
                ('nums_of_vists', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
