# Generated by Django 3.2 on 2023-07-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='nums_of_vists',
        ),
        migrations.AddField(
            model_name='url',
            name='nums_of_visits',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество посещений'),
        ),
    ]
